# генерирует промпты катсцен/портретов уровня 7 (tools/p7/*.txt)
R = 'C:/Users/gulev/CRM/valera-game'
STYLE = 'Detailed 16-bit pixel-art, same style and palette as the game references.'
GREEN = 'Flat solid pure green #00FF00 background (RGB 0,255,0), wide green margins, nothing cut off, no text, no grid lines, every object fully separated.'
COMIC = f'detailed pixel-art comic style like {R}/art_src/comic4_raid.png'
HERO = f'the dirty hero from {R}/art_src/l6/v6_run.png'
OUT = lambda n: f'\nOutput ONE image, saved as PNG at {R}/art_src/l7/{n}.png and print the final path. Do not ask questions.\n'

P = {
'c01_road': f"""Generate ONE wide background image (landscape 3:2) for a 2D side-scrolling game cutscene: a two-lane asphalt ROAD at the edge of a northern pine-birch FOREST at sunset, side view (flat platformer camera): forest behind, road shoulder with gravel and a road sign post (no text), the asphalt road occupies the bottom 20%. Same forest look as {R}/art_src/l6/forest_tall.png. {STYLE} No text.""" + OUT('road7'),
'c02_cars': f"""Generate ONE pixel-art sheet for a 2D side-scrolling game cutscene. {STYLE} {GREEN}
Layout: 2 rows x 3 columns, equal cells, side views facing RIGHT, all on the same baseline, same scale (the minibus is only slightly taller than a standing man).
(1) SILVER minibus van like an old Volkswagen Transporter T4 (no logos), side sliding door closed, two men visible through the windshield; (2) the same van with the side sliding door OPEN, dark interior; (3) the big BIKER from {R}/art_src/biker.png riding a heavy black chopper motorcycle; (4) the same biker on the motorcycle with a second man sitting behind him; (5) a burly man in a black leather biker outfit (leather cap, sunglasses, leather vest with chrome studs, leather trousers, fully clothed, family-friendly), standing on the roadside hitchhiking with a thumb up; (6) the same leather man running happily.""" + OUT('cars7'),
'c03_van': f"""Generate ONE comic panel image (landscape 3:2), {COMIC}: INSIDE a silver minibus van driving along a road at sunset. Front seats: the DRIVER Stas (looks like the man in photo {R}/art_src/refs/l7/stas.jpg: young adult man, short brown hair, light blue eyes, light stubble, dark hoodie) holding the wheel and smiling, and the PASSENGER Maxim (looks like the man in photo {R}/art_src/refs/l7/maxim.jpg: adult man, very short dark hair, full dark beard, white t-shirt, sunglasses on his head). In the back seat sits {HERO} with arms crossed, grumpy. A small air freshener hangs from the mirror: a red-and-green striped pennant with a white folk ornament stripe (hint of Belarus). Leave empty space at the top for speech bubbles. No text.""" + OUT('comic_van'),
'c04_gate': f"""Generate ONE comic panel image (landscape 3:2), {COMIC}: evening at the entrance of a pompous red-brick factory administration building (like photo {R}/art_src/refs/l7/zavod.jpg, clock and flag on top). Rich guests in suits and evening dresses walk in, black luxury cars parked. At a checkpoint turnstile stand two special-forces soldiers from {R}/art_src/commandos.png; one holds a tablet showing a pencil identikit sketch of a mustached face with a big red X. In the foreground, seen from behind, {HERO}. Leave space at the top for speech bubbles. No readable text.""" + OUT('comic_gate'),
'd01_stage': f"""Generate ONE comic panel image (landscape 3:2), {COMIC}: a grand soviet ASSEMBLY HALL with red velvet curtains and a stage; rows of rich elite guests seen from behind. On the stage, two presenters by a lectern with a big projection screen showing a factory turning into a futuristic biotech lab: (left) Denis Ch. - the BALD man on the right in photo {R}/art_src/refs/l7/denis_o_ch.jpg (round face, bald head, friendly smile), wearing a white lab coat; (right) Denis O. - the man with longer dark hair and short beard on the left in that photo, wearing a black tuxedo with a bow tie. High above in a dark balcony, hidden in shadow, stands a mysterious man in a suit whose face is completely hidden in darkness; only one shiny BIOMECHANICAL metal hand is visible, rubbing it against the other hand. Leave space at the top for speech bubbles. No readable text.""" + OUT('comic_stage'),
'd02_shout': f"""Generate ONE comic panel image (landscape 3:2), {COMIC}: in a grand assembly hall full of rich guests in suits, {HERO} stands up among the seats, furious, shouting with a raised fist; guests turn around shocked. In the background on the stage the two presenters (bald man in a white lab coat and a man in a tuxedo with a bow tie, from {R}/art_src/refs/l7/denis_o_ch.jpg) look frightened and start running behind the curtain. Leave space at the top for speech bubbles. No readable text.""" + OUT('comic_shout'),
'd03_raid': f"""Generate ONE comic panel image (landscape 3:2), {COMIC}: chaos in the grand assembly hall: special-forces soldiers from {R}/art_src/cmd_rope.png rappel down on ropes from the ceiling and shoot glowing green dart guns at the rich guests; the hit guests turn into cartoonish green ZOMBIES in suits and evening dresses (family-friendly, funny, no gore) like {R}/art_src/zomb_a.png. In front, the commander in a beret points at the viewer and shouts. Leave space at the top for speech bubbles. No readable text.""" + OUT('comic_raid'),
'e01_portraits': f"""Generate ONE image (landscape 3:2) with a grid of 6 square PORTRAITS (head and shoulders, facing the viewer, plain dark background in each cell) for game dialog boxes, 2 rows x 3 columns, equal cells, detailed pixel-art in the style of {R}/assets/spr/p_vova6.png and {R}/assets/spr/p_biker.png:
(1) Stas - young adult man from photo {R}/art_src/refs/l7/stas.jpg (short brown hair, light blue eyes, light stubble, dark hoodie);
(2) Maxim - adult man from photo {R}/art_src/refs/l7/maxim.jpg (very short dark hair, full dark beard, white t-shirt, sunglasses on head);
(3) Denis Ch. - the BALD man on the right in photo {R}/art_src/refs/l7/denis_o_ch.jpg, white lab coat;
(4) Denis O. - the man with longer dark hair and short beard on the left in that photo, black tuxedo, bow tie;
(5) Mister X - man in a dark suit, face completely hidden in black shadow, one biomechanical metal hand raised;
(6) a burly man in a black leather cap and sunglasses, leather vest with studs (family-friendly).
No text. Thin black lines between cells.""" + OUT('portraits7'),
}
for k, v in P.items():
    open(f'{R}/tools/p7/{k}.txt', 'w', encoding='utf-8').write(v)
print(len(P))
